### ISSUE TITLE
update() fails when CSV contains just header.

### ISSUE THREAD

**Issue by nm1291** [Marcus-Rosti/CS_5010_Project#12]
When CSV contains just header, and no observations.

Traceback (most recent call last):
  File "controller.py", line 36, in <module>
    main()
  File "controller.py", line 30, in main
    run_update_process("../data/SampleCSV.csv")
  File "controller.py", line 15, in run_update_process
    (start_time, end_time) = common_lib.update(update_file)
  File "/home/nikhil/Documents/CS5010/Project/CS_5010_Project/src/common_lib.py", line 24, in update
    start_time = max(times)
ValueError: max() arg is an empty sequence

**Comment by nm1291** [comment]
Ideally in this scenario, we should fetch as much data as possible from the api. So the start date should be a very old date. (Like Jan 1 1960 or whatever is the unix epoch)

**Comment by Marcus-Rosti** [comment]
Resolved with ecea7c9
